### ISSUE TITLE
Can we do without a WeakValueDictionary in ProxyDb?

### ISSUE THREAD

**Issue by Korijn** [Korijn/observ#108]
https://github.com/fork-tongue/observ/blob/95756af080acec21fca4e2853e7a64e0031f6da9/observ/proxy_db.py#L61

I wonder if this can be a plain dict (because they're much faster)

**Comment by berendkleinhaneveld** [comment]
Interesting! Might not be needed indeed... i guess we put it in there to release unused references to proxies, but since proxies share the same target, it shouldn't have a lot of overhead. And there can be 4 variants anyways: readonly/shallow. You could just try to change it and see if the testsuite still runs. There are some (regression) tests concerning this, I believe.

**Comment by berendkleinhaneveld** [comment]
I just tried, and it seems to make it a lot slower actually (about 10x or more). Don't know exactly what's going on here.

**Comment by Korijn** [comment]
I've thought about it some more, and it doesn't make sense. The proxies keep a reference to `target`, so it will mess with the gc mechanics we've implemented.
