### ISSUE TITLE
More detailed watch callback

### ISSUE THREAD

**Issue by berendkleinhaneveld** [Korijn/observ#33]
It would be useful to have more detailed info for watch callbacks on collections to have a better understanding what has changed. Currently, the callback for arrays yields new and old objects but they are usually the same because they point to the same object. I think this is also the case for dicts.

Especially for dicts it would be beneficial to know for which keys the values have changed, which key/value pairs have been added and which key/value pairs have been removed. For arrays the same applies, but then you would expect indices of course.

**Comment by Korijn** [comment]
I wonder how this works in vue (3)...

I checked it out; same story! I also think instead of trying to solve this, instead you would need render functions so that all you need (in user code) is the _new_ state, and you let the framework diff the old and new output of the render function, and make updates to the UI. This is in essence what vue provides on top of the reactive core, which is really all observ is so far. The goal is to never ever manually diff/sync state to the view in user code.

**Comment by berendkleinhaneveld** [comment]
My idea was that because you have all these proxy methods for all readers and writers, it might be possible to create a quite performant diff. Diffing in user land / render will probably take a bit more processing. Although that of course depends on how detailed that diff needs to be.
