### ISSUE TITLE
Memory leak with QTimer

### ISSUE THREAD

**Issue by Korijn** [Korijn/observ#76]
We might have the same issue as https://github.com/fork-tongue/collagraph/pull/49

https://github.com/fork-tongue/observ/blob/b3c0e62fe6be3254c6d5b3af9c98460dbd7c1e14/observ/scheduler.py#L49

**Comment by berendkleinhaneveld** [comment]
I don't think we have the same problem here actually: this is a method that is (or should) called only once and then the flush method from the global `scheduler` instance is connected. This global object is never ever destroyed anyways, so it is a different situation than in collagraph. When we would make the scheduler non-global, then we might want to look into it, but now that we have QtAsyncio this method will serve as fallback anyways, so I'm closing this issue for now. 
Feel free to reopen if you feel otherwise.
